#!/bin/bash -e

VARIANT=$1

UNAME=$(uname)
BASE_URL="http://download.qt.io/snapshots/ci/qtwebkit/5.212/1567427726/qtwebkit"
if [ "$UNAME" = "Darwin" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-MacOS-$VARIANT.7z"
elif [ "$UNAME" = "Linux" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-Linux-$VARIANT.7z"
elif [ "${UNAME:0:4}" = "MSYS" -o "${UNAME:0:5}" = "MINGW" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-Windows-$VARIANT.7z"
else
  echo "Unsupported system." >&2
  exit 1
fi

ARCHIVE=$(basename $DOWNLOAD_URL)

pushd $QTDIR

echo Downloading QtWebKit
curl --progress-bar -L -o $ARCHIVE ${DOWNLOAD_URL} || exit 1

echo Installing QtWebKit
7z x $ARCHIVE
rm -f $ARCHIVE

popd
