#!/bin/bash -e

UNAME=$(uname)
BASE_URL="http://download.qt.io/snapshots/ci/qtwebkit/5.212/1563413169/qtwebkit"
if [ "$UNAME" = "Darwin" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-MacOS-MacOS_10_13-Clang-MacOS-MacOS_10_13-X86_64.7z"
elif [ "$UNAME" = "Linux" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-Linux-RHEL_7_6-GCC-Linux-RHEL_7_6-X86_64.7z"
elif [ "${UNAME:0:4}" = "MSYS" -o "${UNAME:0:5}" = "MINGW" ]; then
  DOWNLOAD_URL="$BASE_URL/qtwebkit-Windows-Windows_10-MSVC2017-Windows-Windows_10-X86_64.7z"
else
  echo "Unsupported system." >&2
  exit 1
fi

ARCHIVE=$(basename $DOWNLOAD_URL)

pushd $QTDIR/$COMPILER

echo Downloading QtWebKit
curl --progress-bar -L -o $ARCHIVE ${DOWNLOAD_URL} || exit 1

echo Installing QtWebKit
7z x $ARCHIVE
rm -f $ARCHIVE

popd
